### PR TITLE
Add R code examples

### LINKED ISSUE #8: R code
Hi Asjad,

Thanks for putting together this excellent public good. 

Would you be open to adding R code examples that match the existing Stata pages on the site? 

I know most of the packages quite well and should be able to get a PR submitted fairly quickly if you're up for it.

The main structural thing we'd have to think about ahead of time is organization of the repo for navigation. E.g. Would you want (tabbed?) R and Stata code on the same page, or should they just resolve to separate subdirs?

### PR DESCRIPTION
**Pull request by grantmcdermott**
Closes #8 

Sorry this has taken me longer than expected @asjadnaqvi . I've been too busy with a new job and family visiting.

This is still a WIP in the sense that I (a) need to add several packages/estimators and (b) need to flesh out the text for several pages that I _have_ provided the code for. OTOH adding the text for the (b) cases should be pretty quick if either of us have time.

### CODE REVIEW

**Comment by asjadnaqvi** [comment]
@grantmcdermott I will give you admin rights to the repository so you can add pages etc. rather we do multiple PRs for modifications etc.

**Comment by grantmcdermott** [comment]
Brilliant, thanks @asjadnaqvi. I'll try to tie up the examples that I have for this PR so far, submit it, and then try to get to the others further down the line. Cheers.

**Comment by grantmcdermott** [comment]
Okay, I finally carved out the time to finish the write-ups for these examples. There are obviously still more R-based pages to add, but I think it would be good to get these up at least. @asjadnaqvi please review and feel free to merge when you're happy.

PS. Do you want me to add a comment to README, or claim responsibility for the R code examples somewhere? I'm not particularly phased about attribution. But it may be helpful for you (or readers) if there questions/problems, so people know who to direct these too.

**Comment by asjadnaqvi** [comment]
@grantmcdermott I will merge the PR. But also gave you the admin rights to the repo this yourself. In case you make changes etc, you can directly push them yourself.

**Comment by asjadnaqvi** [comment]
@grantmcdermott, off topic question, but since I recent read your climate econ papers, let me know if you have some thoughts on how to partition and organize this repository:
https://github.com/asjadnaqvi/climate-econ

I will eventually move it to a more dynamic website which parses .bib files rather than have my RAs manually format each entry.

**Comment by grantmcdermott** [comment]
Oh, wow that looks ace. I'll think it too. (Maybe a quarto.org based website for automatic .bib parsing?)

**Comment by asjadnaqvi** [comment]
A couple of ppl recommended Quarto. Checking it out for templates etc. If you come across something relevant please let me know!

**Pull request merged**
